### ISSUE TITLE
Demo code?

### ISSUE THREAD

**Issue by nathanbriggs** [FernleafSystems/ApiWrappers-FreeAgent#1]
Hi Paul,

(Imagine me offering a cupcake with a cherry on top) Any chance of a little demo code to get us started, please?

The ol' brainbox ain't what it used to be :-)  A quick demo covering the auth procedure and, eg running a simple query, would be really helpful

Hugs,
Nathan

**Comment by paulgoodchild** [comment]
It's coming, I promise. I've held off because it's in flux at the moment.

Make sure if you're using composer you're strict with version requirements as things may break as it develops. As it stands right now, it's pretty good. Will try to get something out there asap. Thanks! :)
